---
title: "기계와 인간"
output: html_document
date: "2025-09-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

강의개요 : 루돌로지, 존재론, 정치철학

강의계획서 줄임

다루는 사람 : 라투르, 레비 브라이언트, 도나헤이웨이, 그레이엄 하먼

라투르는 꼼꼼히읽어야함 비유가많고 좀 그렇다

번역자가 ㅄ이였음 치명적인 오역들이 많다.

정 반대로 한 게 많아서

강의 방식 :

1시간 : 발제

2시간 : 토론

3시간 : 교수

이번학긴 텍스트로 직접 뛰어들기보단, 발자제의 그것?

감성 인공지능.. 대학원

틀리고, 모르는 것에 대해서 걱정하지마라.

내가 이걸 장악하지 못한다는 것을 보이는 것이 발제다.

15주차 후 보고서 제출

1.  브뤼노 라투르(bruno Latour)

    \<우리는 결코 근대인었던 적 이 없다.

2.  레비 브라이언트

    \<존재의 지도\>

위에 두 책 사기

1.  그레이엄 하먼(마지막장)

    \<네트워크의 군주\>

2.  도나 헤러웨이(첫 장)

    \<헤러웨이 선언문\>

사실 우리는 아직 근대성(모더니즘(근대에살고있다)

아이브도 그렇다. 욜로,

술술읽힌다고 절대 그렇게 읽으면 안됌

매체가 메세지다

모든 것은 매게자다

근대부터 주체와 객체의 이분법, 이질적인 존재로 나눔

비대칭성이 발생 다르니까. 사실은 그렇지 않다고

근대적 도식을 깨고 행위자 연결망

그 이론이 신 유물론보다 선행해서. \
사실 난이도만 보면 레비 브라이언트의 신 유물론이 더쉬움 but!

영미철학이 더 쉬움. 프랑스철학 ㅈㄴ어려움

레비는 우리가 마주하는 존재는 모두 매체다 기계다. 기계존재론

엔트로피(무질서)

하먼은 신유물론자가 아닌데도 불구하고,

2차문헌을 통해서만 습득해서,

다음강의 우결그 2장(반드시 읽기 난 못간다)

헌번개념이 뭔지 /

미리 40\~50페이지 읽고오기

수강 유의 사항 : 평등 존중 사유

자기 과시가 아니라 서로의 사유를 발전시키는 데 있다.

## Medieval Era(근대를 알면 중세를 알아야지)

최건을 알려면 최건을 아닌사람을 알아야함

중세 특징: 아우구스티누스, 아퀴나스 -\> 신앙, 계시(우리는 현재 직관이라고 말함)

인식할때 조차도 신앙이 중요하다!

(우리는 현재 직관이라고 말함). 내가 떠오르는 건 계시이다.

순종.(수동적인 존재가 되어야합니다.

믿음, 계시, 순종, (인식론 존재론, 윤리학)

신으로부터 탈주하고싶고, 독립하고싶은사람

여기서부터 르네상스!!

과학적 사실, 자연의 법칙 알게됨. 신한테 의지가 왜필요하나!!

## Moderen Era

데카르트가 열었다.

주체(주인), subject.

sub(아래 놓여있는) 기체 개념이였음!

안경, 내 마우스 이건 내가 아님. 본질이 아니다

필연적인 것이 아님. 필연적으로 변하지 않는 본질이 있다는 건데

기체가 떠받치고있다라는게, 근데 이것이 근대로 오며 주체라는 개념으로 바뀜

인간만 그것을 가지고있는 것 같아서

주체의 시대

주체인 것과 주체아닌 것의 시대

주체를 알려면 주체가 아닌 것 . 객체를 알아ㅑ지

객체는 손님의 개념임. Object

근대 : 주체/객체 이분법의시대

인간의 이성으로 산업혁명 되잖아. 신 이야기 하지말고

어 그러고 보니 인간 아닌 것이 있네

인간 : 주체

인간x : 객체

이렇게 심각하게 나뉨

중세때는 책상도 신의 피조물이고,\~\~

어 인간이 더 쎄네\~

동물, 흑인, 여성도 인간의 범주에서 배제되었음 객체가 되었음

여기서 말한 주체는 더욱 좁음

가요 들으면 전부 인간은주체성!이럼

여전히 모더니즘 시대라느거알수있음

예능 봐라! 긍정적인게 뭐냐
인기<->비인기

수동적인거있으면 바로 패널들이 비판함. 움직여야합니다\~

예전엔 백인, 남성 귀족이였음

주체한텐 이성

---
하먼 : 라투르, 레비 브라이언트 처럼 관계에만 집중
하면 개별 사물의 파악되지 않는 매개되지 않는
무엇을 놓친다. 불의 연소를 알아도, 보이지 않는 것이 있음
이것을 탐구해야함 더 깊은 존재론적 질문을 던짐